package io.github.reinershir.boot.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import io.github.reinershir.boot.model.SystemLog;
import org.springframework.stereotype.Repository;
/**
 * 系统日志 Mapper, generated by Shir Boot
 * @author Shir-Boot
 **/
 @Repository
public interface SystemLogMapper extends BaseMapper<SystemLog> {

}
