package io.github.reinershir.ai.service;
import java.util.List;

import com.baomidou.mybatisplus.extension.service.IService;
import com.unfbx.chatgpt.entity.chat.Message;

import io.github.reinershir.ai.entity.WebRequestMessage;
import io.github.reinershir.ai.model.ChatHistory;

/**
 * ChatHistory Service, generated by Shir Boot EasyGenerator
 * @author Shir-Boot
 * @version 1.0
 *
 */
public interface ChatHistoryService extends IService<ChatHistory>{
	
	/**
	* @Function: ChatHistoryService.java
	* @Description:  save the chat history
	* @param: @param request requestParams
	* @param: @param message prompt
	* @param: @param userId
	* @param: @param allMessage chat context
	* @param: @return
	* @return：boolean
	* @version: v1.0.0
	* @author: ReinerShir
	* @date: 2024年7月30日 下午10:05:04 
	* Modification History:
	* Date         Author          Version            Description
	*---------------------------------------------------------*
	* 2024年7月30日   ReinerShir       v1.0.0              修改原因
	 */
	public boolean saveChatHistory(WebRequestMessage request,StringBuffer message,Long userId,List<Message> allMessage);
	
	public boolean saveChatHistory(String sessionId,String model,String promot,String mask,StringBuffer message,Long userId,List<Message> allMessage);
}
